### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by k1bac** [DevOFVictory/SchoolAPI#1]
Greetings, i am very interested in using your API for further development of a discord bot which could display information gathered from your API. Thing is, i am not very experienced and since your How To: is set to coming soon i just wanted to ask when you would be able to catch up with that of provide some basic documentation for me and others to work with.

**Comment by mafeth** [comment]
Hey, do you need the docs for the Rest JSON Module first, or for the Java/Kotlin library?

**Comment by k1bac** [comment]
I need everything i can get. As you can see in my account i only ever dealt with python and some c++, javascript, so i'll take any help you can offer. Maybe the docs for the library would be more practical than the JSON Module. Thank you!

**Comment by mafeth** [comment]
Honestly, I don't want to create a documentation for this whole project, since I didn't work on it for a month. If you can  tell, what modules/functions of the api you need, I can create docs especially for these.

**Comment by k1bac** [comment]
My plan is to use your function of taking a picture of the "Units Vertretungsplan" and post it in discord channel. So I basically only need guidance on how to get an image of that page. I can figure out everything else, i hope.

**Comment by mafeth** [comment]
Please add me on discord. (DevOFVictory#7897) I figured out, that the "Units Vertretungsplan" have multiple versions and the api is only compatible with the one, my school uses, but I can help you to program it, because I have already done this. :)

**Comment by k1bac** [comment]
Added you
